### ISSUE TITLE
Doesnt "unstuck" when in spectator mode as advertised

### ISSUE THREAD

**Issue by Dragonissa** [jobggun/Sourcemod-Anti-Unassigned-Stuck#2]
The plugin advertises that it unstucks you if you are either in the unassigned or spectator team. This is only partially true since in the code it only checks if you are in "TFTeam_Unassigned" but not "TFTeam_Spectator".

Would recommend changing line [#88](https://github.com/jobggun/Sourcemod-Anti-Unassigned-Stuck/blob/main/sourcemod/scripting/antiuastuck.sp#L88) and [#119](https://github.com/jobggun/Sourcemod-Anti-Unassigned-Stuck/blob/main/sourcemod/scripting/antiuastuck.sp#L119) to

`if(TF2_GetClientTeam(client) == TFTeam_Unassigned || TF2_GetClientTeam(client) == TFTeam_Spectator)`

**Comment by jobggun** [comment]
Actually, if you're in proper spectator team, you can change your team without problems. I meant spectator team as 'a team like spectator team' as you can't not spawn to red or blue. Thus i don't think we need to change those codes.

**Comment by Dragonissa** [comment]
Not really since there are certain conditions which fail to trigger the VGUI even tho you are in spectator mode. But that's not part of this plugin.
